import type {Metadata} from 'next';
import {User} from '../types';
import {API_URL} from '../config';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({children}: LayoutProps<'/'>) {
  const userResponse = await fetch(API_URL + '/users/me');
  if (!userResponse.ok) {
    throw new Error(userResponse.statusText);
  }
  const user = (await userResponse.json()) as User;

  return (
    <html lang="en">
      <body>
        <div className="max-w-xl mx-auto py-20 px-10">
          <header className="flex justify-between items-center">
            <h1>Arrrbnb</h1>
            <p>
              {user.firstName} {user.lastName}
            </p>
          </header>
          <div className="mt-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
